# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""
Emit force/release pairs for reset-less FFs (dfxtp_*) in the post-PnR netlist.

dfxtp_* has no reset pin, so Q starts X in 4-state sim and stays X if it
self-references (e.g. clk_sample_div +3 counter) — deadlocks audio. We emit
gl_init_force.vh / gl_init_release.vh for the GL testbench to force Q=0 at
t=0 and release after settle. SKY130's functional Q is a wire fed by `buf`
from a UDP, so only `force` works (procedural assignment to a wire is illegal).
"""

import re
import sys
from pathlib import Path

NETLIST = Path("runs/wokwi/final/pnl/tt_um_kolontsov_journey.pnl.v")
OUT_FORCE = Path("test/gl_init_force.vh")
OUT_RELEASE = Path("test/gl_init_release.vh")

# sky130_fd_sc_hd__dfxtp_<drive> <inst_name> ( ... );
RE_DFXTP = re.compile(r"sky130_fd_sc_hd__dfxtp_\w+\s+(\S+)\s*\(")


def main() -> int:
    if not NETLIST.exists():
        sys.stderr.write(
            f"netlist not found: {NETLIST}\nrun `make harden` first.\n"
        )
        return 1

    text = NETLIST.read_text()
    insts = RE_DFXTP.findall(text)
    if not insts:
        sys.stderr.write("no dfxtp_* instances found — netlist format changed?\n")
        return 1

    OUT_FORCE.write_text(
        "// Auto-generated by scripts/gen_gl_init.py — do not edit.\n"
        f"// {len(insts)} reset-less FFs, forced to 0 at t=0.\n"
        + "".join(f"force dut.{n}.Q = 1'b0;\n" for n in insts)
    )
    OUT_RELEASE.write_text(
        "// Auto-generated by scripts/gen_gl_init.py — do not edit.\n"
        + "".join(f"release dut.{n}.Q;\n" for n in insts)
    )
    print(f"emitted {len(insts)} init pairs → {OUT_FORCE.name}, {OUT_RELEASE.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
