/*
 * Copyright (c) 2026 Vadim Kolontsov
 * SPDX-License-Identifier: Apache-2.0
 *
 * Cat balloon sprite. Generated by scripts/gen_cat_sprite.py.
 *
 * Two compact bitplanes (51x26) encode a filled silhouette: at sample
 * time `hi & ~lo` selects outline (pv=1), `lo` selects fill (pv=2). A
 * sparse pv=3 accent overlay restores highlights/cheeks. The 6-state
 * cat_frame uses a 3-bit encoding so two codes stay don't-care for the
 * body sig-mask predicates.
 *
 * Owns cat_y_r and cat_frame; exports cat_rel_x/cat_rel_y so cat_speech
 * can chain its offset off the shared base. Drift is computed in
 * pixel_shader and folded into cat_rel_*.
 */

`default_nettype none

module cat_sprite (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        frame_tick,
    input  wire        phase_cat_vis,
    input  wire        phase_cat_in_start,
    input  wire        phase_cat_move,     // is_cat_in | is_cat_out
    input  wire        anim_sub_tick,      // 1 once per 4 frames (ctr[1:0]==3)
    input  wire [2:0]  drift_x,            // 0..7 sprite-px x-sway (frame-stable)
    input  wire [2:0]  drift_y,            // 0..7 sprite-px y-sway (frame-stable)
    input  wire [9:0]  pixel_x,
    input  wire [9:0]  pixel_y,
    output wire [9:0]  cat_rel_x,          // pixel_x - CAT_X, for speech chain
    output wire [9:0]  cat_rel_y,          // pixel_y - cat_y_r, for speech chain
    output reg  [1:0]  r,
    output reg  [1:0]  g,
    output reg  [1:0]  b,
    output wire        visible             // gated by 104x204 bbox
);

    localparam [9:0] CY_BOT = 10'd484;
    localparam [9:0] Y_STEP = 10'd3;

    // CAT_X = 80 = 64+16 (2 set bits) — sparser than 76 makes the
    // pixel_x-CAT_X subtract cheaper; 4 px shift is imperceptible.
    localparam [9:0] CAT_X    = 10'd80;
    localparam int   CAT_PX_W = 104;    // 26 * 4
    localparam int   CAT_PX_H = 204;    // 51 * 4

    logic [9:0] cat_y_r;
    logic [2:0] cat_frame;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            cat_y_r   <= CY_BOT;
            cat_frame <= 3'd0;
        end else if (frame_tick) begin
            if (phase_cat_in_start)
                cat_y_r <= CY_BOT;
            else if (phase_cat_move)
                cat_y_r <= cat_y_r - Y_STEP;

            if (phase_cat_vis & anim_sub_tick) begin
                case (cat_frame)
                    3'd0:    cat_frame <= 3'd1;
                    3'd1:    cat_frame <= 3'd3;
                    3'd3:    cat_frame <= 3'd7;
                    3'd7:    cat_frame <= 3'd6;
                    3'd6:    cat_frame <= 3'd4;
                    3'd4:    cat_frame <= 3'd0;
                    default: cat_frame <= 3'd0;
                endcase
            end
        end
    end

    // bbox uses single-sided unsigned compare: underflow wraps high so
    // the same check rejects above- and below-sprite. drift_{x,y} <<2
    // upgrades sprite-pixel units to real px before subtracting.
    assign cat_rel_x = pixel_x - CAT_X   - {5'd0, drift_x, 2'd0};
    assign cat_rel_y = pixel_y - cat_y_r - {5'd0, drift_y, 2'd0};
    wire       cat_in = (cat_rel_x < 10'(CAT_PX_W)) & (cat_rel_y < 10'(CAT_PX_H));
    wire [4:0] sx     = cat_rel_x[6:2];
    wire [5:0] sy     = cat_rel_y[7:2];

    // Alias for the generated body block, which references `frame`.
    wire [2:0] frame = cat_frame;

    // ---- Body (per-frame residue, signature-mask delta) ----
    // Signature predicates: body bitplane lo
    wire body_sig_lo_0 = 1'b1;  // frames [0, 1, 2, 3, 4, 5]
    wire body_sig_lo_1 = ~frame[0];  // frames [0, 4, 5]
    wire body_sig_lo_2 = frame[0];  // frames [1, 2, 3]
    wire body_sig_lo_3 = frame[2];  // frames [3, 4, 5]
    wire body_sig_lo_4 = ~frame[2];  // frames [0, 1, 2]
    wire body_sig_lo_5 = ((~frame[1] & frame[0]) | (frame[2] & ~frame[1]));  // frames [1, 5]
    wire body_sig_lo_6 = ~frame[1];  // frames [0, 1, 5]
    wire body_sig_lo_7 = (~frame[2] & ~frame[0]);  // frames [0]
    wire body_sig_lo_8 = ((~frame[1] & frame[0]) | (frame[2] & ~frame[0]));  // frames [1, 4, 5]
    wire body_sig_lo_9 = ((frame[1] & ~frame[0]) | (~frame[2] & ~frame[0]));  // frames [0, 4]
    wire body_sig_lo_10 = (frame[1] & ~frame[0]);  // frames [4]
    wire body_sig_lo_11 = (frame[0] | frame[2]);  // frames [1, 2, 3, 4, 5]
    wire body_sig_lo_12 = ((~frame[2] & frame[0]) | (frame[2] & ~frame[1]));  // frames [1, 2, 5]
    wire body_sig_lo_13 = ((frame[1] & frame[0]) | (~frame[2] & ~frame[0]));  // frames [0, 2, 3]
    wire body_sig_lo_14 = (~frame[2] & frame[1]);  // frames [2]
    wire body_sig_lo_15 = (frame[2] & frame[1]);  // frames [3, 4]
    wire body_sig_lo_16 = (~frame[0] | ~frame[1]);  // frames [0, 1, 4, 5]
    wire body_sig_lo_17 = (frame[2] & frame[0]);  // frames [3]
    wire body_sig_lo_18 = (frame[1] & frame[0]);  // frames [2, 3]

    // Signature predicates: body bitplane hi
    wire body_sig_hi_0 = 1'b1;  // frames [0, 1, 2, 3, 4, 5]
    wire body_sig_hi_1 = ~frame[0];  // frames [0, 4, 5]
    wire body_sig_hi_2 = frame[0];  // frames [1, 2, 3]
    wire body_sig_hi_3 = ~frame[2];  // frames [0, 1, 2]
    wire body_sig_hi_4 = ((~frame[1] & frame[0]) | (frame[2] & ~frame[1]));  // frames [1, 5]
    wire body_sig_hi_5 = ~frame[1];  // frames [0, 1, 5]
    wire body_sig_hi_6 = (~frame[2] & ~frame[0]);  // frames [0]
    wire body_sig_hi_7 = ((~frame[1] & frame[0]) | (frame[2] & ~frame[0]));  // frames [1, 4, 5]
    wire body_sig_hi_8 = (~frame[0] | ~frame[1]);  // frames [0, 1, 4, 5]
    wire body_sig_hi_9 = frame[2];  // frames [3, 4, 5]
    wire body_sig_hi_10 = (frame[1] & ~frame[0]);  // frames [4]
    wire body_sig_hi_11 = ((~frame[2] & frame[0]) | (frame[2] & ~frame[0]));  // frames [1, 2, 4, 5]
    wire body_sig_hi_12 = (~frame[2] & frame[1]);  // frames [2]
    wire body_sig_hi_13 = frame[1];  // frames [2, 3, 4]
    wire body_sig_hi_14 = (frame[0] | frame[2]);  // frames [1, 2, 3, 4, 5]
    wire body_sig_hi_15 = (frame[1] & frame[0]);  // frames [2, 3]
    wire body_sig_hi_16 = (frame[2] & frame[0]);  // frames [3]

    logic [25:0] body_lo_row;
    always_comb begin
        body_lo_row = 26'd0;
        case (sy)
            6'd0: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000780);
            6'd1: body_lo_row = ({26{body_sig_lo_0}} & 26'h0001860);
            6'd2: body_lo_row = ({26{body_sig_lo_0}} & 26'h0002010);
            6'd3: body_lo_row = ({26{body_sig_lo_0}} & 26'h0004008);
            6'd4: body_lo_row = ({26{body_sig_lo_0}} & 26'h0004008);
            6'd5: body_lo_row = ({26{body_sig_lo_0}} & 26'h0008004);
            6'd6: body_lo_row = ({26{body_sig_lo_0}} & 26'h0008004);
            6'd7: body_lo_row = ({26{body_sig_lo_0}} & 26'h0008004);
            6'd8: body_lo_row = ({26{body_sig_lo_0}} & 26'h0008004);
            6'd9: body_lo_row = ({26{body_sig_lo_0}} & 26'h0008004);
            6'd10: body_lo_row = ({26{body_sig_lo_0}} & 26'h0008004);
            6'd11: body_lo_row = ({26{body_sig_lo_0}} & 26'h0004008);
            6'd12: body_lo_row = ({26{body_sig_lo_0}} & 26'h0004008);
            6'd13: body_lo_row = ({26{body_sig_lo_0}} & 26'h0002010);
            6'd14: body_lo_row = ({26{body_sig_lo_0}} & 26'h0001860);
            6'd15: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000480);
            6'd16: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000300);
            6'd17: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000480);
            6'd18: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000780);
            6'd19: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000100);
            6'd20: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000100);
            6'd21: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000100);
            6'd22: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000100);
            6'd23: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000100);
            6'd24: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000100) | ({26{body_sig_lo_1}} & 26'h0c03000);
            6'd25: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000100) | ({26{body_sig_lo_1}} & 26'h1204800) | ({26{body_sig_lo_2}} & 26'h0c03000);
            6'd26: body_lo_row = ({26{body_sig_lo_0}} & 26'h1000900) | ({26{body_sig_lo_1}} & 26'h0108000) | ({26{body_sig_lo_2}} & 26'h0204000);
            6'd27: body_lo_row = ({26{body_sig_lo_0}} & 26'h1000900) | ({26{body_sig_lo_1}} & 26'h00f0000) | ({26{body_sig_lo_2}} & 26'h0108000);
            6'd28: body_lo_row = ({26{body_sig_lo_0}} & 26'h1000900) | ({26{body_sig_lo_2}} & 26'h00f0000);
            6'd29: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000100) | ({26{body_sig_lo_1}} & 26'h2000400) | ({26{body_sig_lo_2}} & 26'h1000800);
            6'd30: body_lo_row = ({26{body_sig_lo_0}} & 26'h2000500) | ({26{body_sig_lo_1}} & 26'h0408000);
            6'd31: body_lo_row = ({26{body_sig_lo_0}} & 26'h2408500) | ({26{body_sig_lo_1}} & 26'h0284000);
            6'd32: body_lo_row = ({26{body_sig_lo_0}} & 26'h2000500) | ({26{body_sig_lo_2}} & 26'h068c000);
            6'd33: body_lo_row = ({26{body_sig_lo_0}} & 26'h2000500) | ({26{body_sig_lo_1}} & 26'h0248000);
            6'd34: body_lo_row = ({26{body_sig_lo_0}} & 26'h0248300) | ({26{body_sig_lo_1}} & 26'h11b0800) | ({26{body_sig_lo_2}} & 26'h2000400);
            6'd35: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000300) | ({26{body_sig_lo_1}} & 26'h0801000) | ({26{body_sig_lo_2}} & 26'h13f8800);
            6'd36: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000100) | ({26{body_sig_lo_1}} & 26'h07fe000) | ({26{body_sig_lo_2}} & 26'h0801000);
            6'd37: body_lo_row = ({26{body_sig_lo_0}} & 26'h0200300) | ({26{body_sig_lo_2}} & 26'h05fe000);
            6'd38: body_lo_row = ({26{body_sig_lo_0}} & 26'h0000300) | ({26{body_sig_lo_3}} & 26'h0204000) | ({26{body_sig_lo_4}} & 26'h0408000);
            6'd39: body_lo_row = ({26{body_sig_lo_0}} & 26'h0040c80) | ({26{body_sig_lo_3}} & 26'h0204000) | ({26{body_sig_lo_4}} & 26'h0408000) | ({26{body_sig_lo_5}} & 26'h0000004) | ({26{body_sig_lo_6}} & 26'h0000008) | ({26{body_sig_lo_7}} & 26'h0000010);
            6'd40: body_lo_row = ({26{body_sig_lo_0}} & 26'h0020080) | ({26{body_sig_lo_3}} & 26'h0244800) | ({26{body_sig_lo_4}} & 26'h0489000) | ({26{body_sig_lo_7}} & 26'h0000060) | ({26{body_sig_lo_8}} & 26'h0000012) | ({26{body_sig_lo_9}} & 26'h0000004) | ({26{body_sig_lo_10}} & 26'h0000008);
            6'd41: body_lo_row = ({26{body_sig_lo_0}} & 26'h00200c0) | ({26{body_sig_lo_3}} & 26'h0244800) | ({26{body_sig_lo_4}} & 26'h0489000) | ({26{body_sig_lo_5}} & 26'h0000002) | ({26{body_sig_lo_7}} & 26'h000000c) | ({26{body_sig_lo_8}} & 26'h0000010) | ({26{body_sig_lo_10}} & 26'h0000001) | ({26{body_sig_lo_11}} & 26'h0000020);
            6'd42: body_lo_row = ({26{body_sig_lo_0}} & 26'h0028080) | ({26{body_sig_lo_3}} & 26'h0244800) | ({26{body_sig_lo_4}} & 26'h0481000) | ({26{body_sig_lo_10}} & 26'h0000003) | ({26{body_sig_lo_12}} & 26'h0000004) | ({26{body_sig_lo_13}} & 26'h0000018) | ({26{body_sig_lo_14}} & 26'h0000020);
            6'd43: body_lo_row = ({26{body_sig_lo_0}} & 26'h0122080) | ({26{body_sig_lo_3}} & 26'h0091000) | ({26{body_sig_lo_4}} & 26'h020c000) | ({26{body_sig_lo_8}} & 26'h0000008) | ({26{body_sig_lo_9}} & 26'h0000020) | ({26{body_sig_lo_14}} & 26'h0000003) | ({26{body_sig_lo_15}} & 26'h0000004) | ({26{body_sig_lo_16}} & 26'h0000010);
            6'd44: body_lo_row = ({26{body_sig_lo_0}} & 26'h00200e0) | ({26{body_sig_lo_3}} & 26'h0000100) | ({26{body_sig_lo_4}} & 26'h0010000) | ({26{body_sig_lo_14}} & 26'h0000001) | ({26{body_sig_lo_17}} & 26'h0000002) | ({26{body_sig_lo_18}} & 26'h0000010);
            6'd45: body_lo_row = ({26{body_sig_lo_0}} & 26'h0020100) | ({26{body_sig_lo_3}} & 26'h0007000) | ({26{body_sig_lo_14}} & 26'h000000c) | ({26{body_sig_lo_18}} & 26'h0000012);
            6'd46: body_lo_row = ({26{body_sig_lo_0}} & 26'h0024100) | ({26{body_sig_lo_3}} & 26'h0000800) | ({26{body_sig_lo_4}} & 26'h0003000) | ({26{body_sig_lo_17}} & 26'h000000c);
            6'd47: body_lo_row = ({26{body_sig_lo_0}} & 26'h0024900);
            6'd48: body_lo_row = ({26{body_sig_lo_0}} & 26'h0024900);
            6'd49: body_lo_row = ({26{body_sig_lo_3}} & 26'h0018600) | ({26{body_sig_lo_4}} & 26'h0024900);
            6'd50: body_lo_row = ({26{body_sig_lo_4}} & 26'h0018600);
            default: begin end
        endcase
    end

    logic [25:0] body_hi_row;
    always_comb begin
        body_hi_row = 26'd0;
        case (sy)
            6'd0: body_hi_row = ({26{body_sig_hi_0}} & 26'h0000780);
            6'd1: body_hi_row = ({26{body_sig_hi_0}} & 26'h0001fe0);
            6'd2: body_hi_row = ({26{body_sig_hi_0}} & 26'h0003ff0);
            6'd3: body_hi_row = ({26{body_sig_hi_0}} & 26'h0007ff8);
            6'd4: body_hi_row = ({26{body_sig_hi_0}} & 26'h0007ff8);
            6'd5: body_hi_row = ({26{body_sig_hi_0}} & 26'h000fffc);
            6'd6: body_hi_row = ({26{body_sig_hi_0}} & 26'h000fffc);
            6'd7: body_hi_row = ({26{body_sig_hi_0}} & 26'h000fffc);
            6'd8: body_hi_row = ({26{body_sig_hi_0}} & 26'h000fffc);
            6'd9: body_hi_row = ({26{body_sig_hi_0}} & 26'h000fffc);
            6'd10: body_hi_row = ({26{body_sig_hi_0}} & 26'h000fffc);
            6'd11: body_hi_row = ({26{body_sig_hi_0}} & 26'h0007ff8);
            6'd12: body_hi_row = ({26{body_sig_hi_0}} & 26'h0007ff8);
            6'd13: body_hi_row = ({26{body_sig_hi_0}} & 26'h0003ff0);
            6'd14: body_hi_row = ({26{body_sig_hi_0}} & 26'h0001fe0);
            6'd15: body_hi_row = ({26{body_sig_hi_0}} & 26'h0000780);
            6'd16: body_hi_row = ({26{body_sig_hi_0}} & 26'h0000300);
            6'd17: body_hi_row = ({26{body_sig_hi_0}} & 26'h0000780);
            6'd18: body_hi_row = ({26{body_sig_hi_0}} & 26'h0000780);
            6'd19: body_hi_row = ({26{body_sig_hi_0}} & 26'h0000100);
            6'd20: body_hi_row = ({26{body_sig_hi_0}} & 26'h0000100);
            6'd21: body_hi_row = ({26{body_sig_hi_0}} & 26'h0000100);
            6'd22: body_hi_row = ({26{body_sig_hi_0}} & 26'h0000100);
            6'd23: body_hi_row = ({26{body_sig_hi_0}} & 26'h0000100);
            6'd24: body_hi_row = ({26{body_sig_hi_0}} & 26'h0000100) | ({26{body_sig_hi_1}} & 26'h0c03000);
            6'd25: body_hi_row = ({26{body_sig_hi_0}} & 26'h0c03100) | ({26{body_sig_hi_1}} & 26'h1204800);
            6'd26: body_hi_row = ({26{body_sig_hi_0}} & 26'h1e07900) | ({26{body_sig_hi_1}} & 26'h0108000);
            6'd27: body_hi_row = ({26{body_sig_hi_0}} & 26'h1f0f900) | ({26{body_sig_hi_1}} & 26'h00f0000);
            6'd28: body_hi_row = ({26{body_sig_hi_0}} & 26'h1fff900);
            6'd29: body_hi_row = ({26{body_sig_hi_0}} & 26'h1fff900) | ({26{body_sig_hi_1}} & 26'h2000400);
            6'd30: body_hi_row = ({26{body_sig_hi_0}} & 26'h3fffd00);
            6'd31: body_hi_row = ({26{body_sig_hi_0}} & 26'h3fffd00);
            6'd32: body_hi_row = ({26{body_sig_hi_0}} & 26'h3fffd00);
            6'd33: body_hi_row = ({26{body_sig_hi_0}} & 26'h3fffd00);
            6'd34: body_hi_row = ({26{body_sig_hi_0}} & 26'h1ffff00) | ({26{body_sig_hi_2}} & 26'h2000000);
            6'd35: body_hi_row = ({26{body_sig_hi_0}} & 26'h0ffff00) | ({26{body_sig_hi_2}} & 26'h1000000);
            6'd36: body_hi_row = ({26{body_sig_hi_0}} & 26'h07fff00) | ({26{body_sig_hi_2}} & 26'h0800000);
            6'd37: body_hi_row = ({26{body_sig_hi_0}} & 26'h03fff00) | ({26{body_sig_hi_2}} & 26'h0400000);
            6'd38: body_hi_row = ({26{body_sig_hi_0}} & 26'h03fff00) | ({26{body_sig_hi_3}} & 26'h0400000);
            6'd39: body_hi_row = ({26{body_sig_hi_0}} & 26'h03fff80) | ({26{body_sig_hi_3}} & 26'h0400000) | ({26{body_sig_hi_4}} & 26'h0000004) | ({26{body_sig_hi_5}} & 26'h0000008) | ({26{body_sig_hi_6}} & 26'h0000010);
            6'd40: body_hi_row = ({26{body_sig_hi_0}} & 26'h03bff80) | ({26{body_sig_hi_3}} & 26'h0400000) | ({26{body_sig_hi_6}} & 26'h0000060) | ({26{body_sig_hi_7}} & 26'h0000002) | ({26{body_sig_hi_8}} & 26'h000001c) | ({26{body_sig_hi_9}} & 26'h0040000);
            6'd41: body_hi_row = ({26{body_sig_hi_0}} & 26'h03bffe0) | ({26{body_sig_hi_3}} & 26'h0400000) | ({26{body_sig_hi_7}} & 26'h0000002) | ({26{body_sig_hi_8}} & 26'h000001c) | ({26{body_sig_hi_9}} & 26'h0040000) | ({26{body_sig_hi_10}} & 26'h0000001);
            6'd42: body_hi_row = ({26{body_sig_hi_0}} & 26'h03bfff8) | ({26{body_sig_hi_3}} & 26'h0400000) | ({26{body_sig_hi_9}} & 26'h0040000) | ({26{body_sig_hi_10}} & 26'h0000003) | ({26{body_sig_hi_11}} & 26'h0000004);
            6'd43: body_hi_row = ({26{body_sig_hi_0}} & 26'h013fff0) | ({26{body_sig_hi_3}} & 26'h0200000) | ({26{body_sig_hi_9}} & 26'h0080000) | ({26{body_sig_hi_12}} & 26'h0000003) | ({26{body_sig_hi_13}} & 26'h0000004) | ({26{body_sig_hi_14}} & 26'h0000008);
            6'd44: body_hi_row = ({26{body_sig_hi_0}} & 26'h003ffe0) | ({26{body_sig_hi_12}} & 26'h0000001) | ({26{body_sig_hi_15}} & 26'h000001e);
            6'd45: body_hi_row = ({26{body_sig_hi_0}} & 26'h003ff00) | ({26{body_sig_hi_15}} & 26'h000001e);
            6'd46: body_hi_row = ({26{body_sig_hi_0}} & 26'h003cf00) | ({26{body_sig_hi_3}} & 26'h0003000) | ({26{body_sig_hi_16}} & 26'h000000c);
            6'd47: body_hi_row = ({26{body_sig_hi_0}} & 26'h003cf00);
            6'd48: body_hi_row = ({26{body_sig_hi_0}} & 26'h003cf00);
            6'd49: body_hi_row = ({26{body_sig_hi_0}} & 26'h0018600) | ({26{body_sig_hi_3}} & 26'h0024900);
            6'd50: body_hi_row = ({26{body_sig_hi_3}} & 26'h0018600);
            default: begin end
        endcase
    end

    // ---- Accent overlay (pv=3 highlights/cheeks, sparse exact plane) ----
    wire accent_sig_0 = 1'b1;  // frames [0, 1, 2, 3, 4, 5]
    wire accent_sig_1 = ~frame[0];  // frames [0, 4, 5]
    wire accent_sig_2 = frame[0];  // frames [1, 2, 3]

    logic [25:0] accent_row;
    always_comb begin
        accent_row = 26'd0;
        case (sy)
            6'd4: accent_row = ({26{accent_sig_0}} & 26'h0000c00);
            6'd5: accent_row = ({26{accent_sig_0}} & 26'h0001800);
            6'd6: accent_row = ({26{accent_sig_0}} & 26'h0001000);
            6'd30: accent_row = ({26{accent_sig_1}} & 26'h0204000);
            6'd31: accent_row = ({26{accent_sig_2}} & 26'h0204000);
            6'd32: accent_row = ({26{accent_sig_1}} & 26'h1803000);
            6'd33: accent_row = ({26{accent_sig_0}} & 26'h1803000);
            6'd34: accent_row = ({26{accent_sig_2}} & 26'h1803000);
            default: begin end
        endcase
    end

    wire accent_bit = accent_row[sx];

    // hi covers outline+interior; ~lo at sample splits outline (pv=1)
    // from interior (pv=2).
    wire body_lo_bit = body_lo_row[sx];
    wire body_hi_bit = body_hi_row[sx] & ~body_lo_bit;
    wire [1:0] body_pv = accent_bit ? 2'd3 : {body_hi_bit, body_lo_bit};

    wire [1:0] pv = body_pv;

    always_comb begin
        case (pv)
            2'd1: begin r = 2'd0; g = 2'd0; b = 2'd0; end
            2'd2: begin
                if (sy < 6'd19) begin
                    r = 2'd3; g = 2'd1; b = 2'd0;
                end else begin
                    r = 2'd2; g = 2'd2; b = 2'd2;
                end
            end
            2'd3: begin
                if (~sy[5]) begin
                    r = 2'd3; g = 2'd3; b = 2'd3;
                end else begin
                    r = 2'd3; g = 2'd2; b = 2'd2;
                end
            end
            default: begin r = 2'd0; g = 2'd0; b = 2'd0; end
        endcase
    end

    assign visible = cat_in & (pv != 2'd0);

endmodule
