/*
 * Copyright (c) 2026 Vadim Kolontsov
 * SPDX-License-Identifier: Apache-2.0
 *
 * Speech balloon. Generated by scripts/gen_speech.py.
 *
 * Frame is arithmetic (no ROM): rectangle with quarter-arc corners and
 * a 4-row staircase tail. Text rendered on top via inline 6x8 ATI font.
 *   sel=0 -> 'LUMOS!', sel=1 -> 'MEEOW!'
 *   46x19 bubble, 8 glyph inline ROM.
 */

`default_nettype none

module cat_speech (
    input  wire       sel,        // 0=LUMOS!, 1=Meow!
    input  wire [5:0] sx,         // 0..45
    input  wire [4:0] sy,         // 0..18
    output reg  [1:0] r,
    output reg  [1:0] g,
    output reg  [1:0] b,
    output wire       visible
);

    // Procedural bubble frame — rectangle body + beveled corners
    // + staircase tail. No ROM. 2-bit palette: 0=trans,1=fill,2=border.
    wire body_y = (sy <= 5'd14);
    wire body_edge = body_y & ((sy == 5'd0) | (sy == 5'd14)
                              | (sx == 6'd0) | (sx == 6'd45));

    // Corner region: 3-wide × 2-tall near each corner of body box.
    // rx/ry = distance from the nearest outer edge (0..2 / 0..1).
    wire near_l = (sx < 6'd3);
    wire near_r = (sx > 6'd42);
    wire near_t = (sy < 5'd2);
    wire near_b = (sy > 5'd12) & body_y;
    wire in_corner = (near_l | near_r) & (near_t | near_b);

    /* verilator lint_off UNUSEDSIGNAL */
    wire [5:0] rx_r_full = 6'd45 - sx;
    wire [4:0] ry_b_full = 5'd14 - sy;
    /* verilator lint_on UNUSEDSIGNAL */
    wire [1:0] rx = near_l ? sx[1:0] : rx_r_full[1:0];
    wire ry = near_t ? sy[0] : ry_b_full[0];

    wire corner_cut = in_corner & (
          ((ry == 1'd0) & (rx == 2'd0))
        | ((ry == 1'd0) & (rx == 2'd1))
        | ((ry == 1'd1) & (rx == 2'd0)));
    wire corner_stair = in_corner & (
          ((ry == 1'd1) & (rx == 2'd1)));

    // Tail (rows BODY_H..BODY_H+3, delta = sy - BODY_H).
    // Per row: left = 6+delta, right = 13-delta. Last row (delta=3)
    // collapses to 2 cells with both as border (tail tip).
    wire in_tail = (sy >= 5'd15) & (sy <= 5'd18);
    wire [1:0] tdelta = sy[1:0] - 2'd3;  // delta 0..3
    wire [3:0] tl = 4'd6  + {2'b0, tdelta};
    wire [3:0] tr = 4'd13 - {2'b0, tdelta};
    wire tail_edge = in_tail & ((sx == {2'b0, tl}) | (sx == {2'b0, tr}));
    wire tail_fill = in_tail & (sx > {2'b0, tl}) & (sx < {2'b0, tr});

    // Tail joint: bottom body row at tail x-range becomes fill (not border).
    wire tail_joint = (sy == 5'd14)
                    & (sx >= 6'd6) & (sx <= 6'd13);

    logic [1:0] frame_pv;
    always_comb begin
        if (corner_cut)                     frame_pv = 2'd0;  // trans
        else if (body_y) begin
            if (tail_joint)                 frame_pv = 2'd1;  // fill
            else if (corner_stair | body_edge) frame_pv = 2'd2;  // border
            else                            frame_pv = 2'd1;  // fill
        end else if (tail_edge)             frame_pv = 2'd2;  // border
        else if (tail_fill)                 frame_pv = 2'd1;  // fill
        else                                frame_pv = 2'd0;  // trans
    end

    // Underflow on tx/ty wraps high so unsigned < doubles as in/out check.
    wire [5:0] tx = sx - 6'd6;
    wire [4:0] ty = sy - 5'd4;
    wire       in_tx = (tx < 6'd36);
    wire       in_ty = (ty < 5'd8);
    wire       in_text = in_tx & in_ty;
    wire [2:0] gy = ty[2:0];

    // Divide-by-6: tx -> (char_pos, gx). Outside [0..35] forced blank.
    logic [2:0] char_pos;
    logic [2:0] gx;
    always_comb begin
        case (tx)
            6'd0: begin char_pos = 3'd0; gx = 3'd0; end
            6'd1: begin char_pos = 3'd0; gx = 3'd1; end
            6'd2: begin char_pos = 3'd0; gx = 3'd2; end
            6'd3: begin char_pos = 3'd0; gx = 3'd3; end
            6'd4: begin char_pos = 3'd0; gx = 3'd4; end
            6'd5: begin char_pos = 3'd0; gx = 3'd5; end
            6'd6: begin char_pos = 3'd1; gx = 3'd0; end
            6'd7: begin char_pos = 3'd1; gx = 3'd1; end
            6'd8: begin char_pos = 3'd1; gx = 3'd2; end
            6'd9: begin char_pos = 3'd1; gx = 3'd3; end
            6'd10: begin char_pos = 3'd1; gx = 3'd4; end
            6'd11: begin char_pos = 3'd1; gx = 3'd5; end
            6'd12: begin char_pos = 3'd2; gx = 3'd0; end
            6'd13: begin char_pos = 3'd2; gx = 3'd1; end
            6'd14: begin char_pos = 3'd2; gx = 3'd2; end
            6'd15: begin char_pos = 3'd2; gx = 3'd3; end
            6'd16: begin char_pos = 3'd2; gx = 3'd4; end
            6'd17: begin char_pos = 3'd2; gx = 3'd5; end
            6'd18: begin char_pos = 3'd3; gx = 3'd0; end
            6'd19: begin char_pos = 3'd3; gx = 3'd1; end
            6'd20: begin char_pos = 3'd3; gx = 3'd2; end
            6'd21: begin char_pos = 3'd3; gx = 3'd3; end
            6'd22: begin char_pos = 3'd3; gx = 3'd4; end
            6'd23: begin char_pos = 3'd3; gx = 3'd5; end
            6'd24: begin char_pos = 3'd4; gx = 3'd0; end
            6'd25: begin char_pos = 3'd4; gx = 3'd1; end
            6'd26: begin char_pos = 3'd4; gx = 3'd2; end
            6'd27: begin char_pos = 3'd4; gx = 3'd3; end
            6'd28: begin char_pos = 3'd4; gx = 3'd4; end
            6'd29: begin char_pos = 3'd4; gx = 3'd5; end
            6'd30: begin char_pos = 3'd5; gx = 3'd0; end
            6'd31: begin char_pos = 3'd5; gx = 3'd1; end
            6'd32: begin char_pos = 3'd5; gx = 3'd2; end
            6'd33: begin char_pos = 3'd5; gx = 3'd3; end
            6'd34: begin char_pos = 3'd5; gx = 3'd4; end
            6'd35: begin char_pos = 3'd5; gx = 3'd5; end
            default: begin char_pos = 3'd0; gx = 3'd0; end
        endcase
    end

    // Text table: {sel, char_pos[2:0]} -> glyph idx (0 = blank)
    logic [3:0] glyph_idx;
    always_comb begin
        case ({sel, char_pos})
            4'b0_000: glyph_idx = 4'd4;  // L
            4'b0_001: glyph_idx = 4'd2;  // U
            4'b0_010: glyph_idx = 4'd1;  // M
            4'b0_011: glyph_idx = 4'd6;  // O
            4'b0_100: glyph_idx = 4'd7;  // S
            4'b0_101: glyph_idx = 4'd8;  // !
            4'b1_000: glyph_idx = 4'd1;  // M
            4'b1_001: glyph_idx = 4'd5;  // E
            4'b1_010: glyph_idx = 4'd5;  // E
            4'b1_011: glyph_idx = 4'd6;  // O
            4'b1_100: glyph_idx = 4'd3;  // W
            4'b1_101: glyph_idx = 4'd8;  // !
            default: glyph_idx = 4'd0;
        endcase
    end

    // Embedded 6x8 font — only the 9 glyphs we actually use.
    // Row LSB = leftmost pixel. Default row = 0 (blank glyph + OOB).
    logic [5:0] glyph_row;
    always_comb begin
        case ({glyph_idx, gy})
            7'd8: glyph_row = 6'b010001;  // M row 0
            7'd9: glyph_row = 6'b011011;  // M row 1
            7'd10: glyph_row = 6'b010101;  // M row 2
            7'd11: glyph_row = 6'b010101;  // M row 3
            7'd12: glyph_row = 6'b010001;  // M row 4
            7'd13: glyph_row = 6'b010001;  // M row 5
            7'd14: glyph_row = 6'b010001;  // M row 6
            7'd16: glyph_row = 6'b010001;  // U row 0
            7'd17: glyph_row = 6'b010001;  // U row 1
            7'd18: glyph_row = 6'b010001;  // U row 2
            7'd19: glyph_row = 6'b010001;  // U row 3
            7'd20: glyph_row = 6'b010001;  // U row 4
            7'd21: glyph_row = 6'b010001;  // U row 5
            7'd22: glyph_row = 6'b001110;  // U row 6
            7'd24: glyph_row = 6'b010001;  // W row 0
            7'd25: glyph_row = 6'b010001;  // W row 1
            7'd26: glyph_row = 6'b010001;  // W row 2
            7'd27: glyph_row = 6'b010101;  // W row 3
            7'd28: glyph_row = 6'b010101;  // W row 4
            7'd29: glyph_row = 6'b010101;  // W row 5
            7'd30: glyph_row = 6'b001010;  // W row 6
            7'd32: glyph_row = 6'b000111;  // L row 0
            7'd33: glyph_row = 6'b000010;  // L row 1
            7'd34: glyph_row = 6'b000010;  // L row 2
            7'd35: glyph_row = 6'b000010;  // L row 3
            7'd36: glyph_row = 6'b000010;  // L row 4
            7'd37: glyph_row = 6'b010010;  // L row 5
            7'd38: glyph_row = 6'b011111;  // L row 6
            7'd40: glyph_row = 6'b011111;  // E row 0
            7'd41: glyph_row = 6'b010010;  // E row 1
            7'd42: glyph_row = 6'b000010;  // E row 2
            7'd43: glyph_row = 6'b001110;  // E row 3
            7'd44: glyph_row = 6'b000010;  // E row 4
            7'd45: glyph_row = 6'b010010;  // E row 5
            7'd46: glyph_row = 6'b011111;  // E row 6
            7'd48: glyph_row = 6'b001110;  // O row 0
            7'd49: glyph_row = 6'b010001;  // O row 1
            7'd50: glyph_row = 6'b010001;  // O row 2
            7'd51: glyph_row = 6'b010001;  // O row 3
            7'd52: glyph_row = 6'b010001;  // O row 4
            7'd53: glyph_row = 6'b010001;  // O row 5
            7'd54: glyph_row = 6'b001110;  // O row 6
            7'd56: glyph_row = 6'b001110;  // S row 0
            7'd57: glyph_row = 6'b010001;  // S row 1
            7'd58: glyph_row = 6'b000001;  // S row 2
            7'd59: glyph_row = 6'b001110;  // S row 3
            7'd60: glyph_row = 6'b010000;  // S row 4
            7'd61: glyph_row = 6'b010001;  // S row 5
            7'd62: glyph_row = 6'b001110;  // S row 6
            7'd64: glyph_row = 6'b000100;  // ! row 0
            7'd65: glyph_row = 6'b001110;  // ! row 1
            7'd66: glyph_row = 6'b001110;  // ! row 2
            7'd67: glyph_row = 6'b000100;  // ! row 3
            7'd68: glyph_row = 6'b000100;  // ! row 4
            7'd70: glyph_row = 6'b000100;  // ! row 6
            default: glyph_row = 6'd0;
        endcase
    end

    wire font_pixel = glyph_row[gx];

    // Text ink only valid inside the bubble's yellow fill region (pv==1).
    wire text_ink = in_text & font_pixel & (frame_pv == 2'd1);
    always_comb begin
        if (text_ink) begin
            r = 2'd0; g = 2'd0; b = 2'd0;
        end else begin
            case (frame_pv)
                2'd1:    begin r = 2'd3; g = 2'd3; b = 2'd0; end  // yellow
                2'd2:    begin r = 2'd0; g = 2'd0; b = 2'd0; end  // black
                default: begin r = 2'd0; g = 2'd0; b = 2'd0; end  // transparent
            endcase
        end
    end

    assign visible = (frame_pv != 2'd0);

endmodule
