/*
 * Copyright (c) 2026 Vadim Kolontsov
 * SPDX-License-Identifier: Apache-2.0
 *
 * Scroller font + text ROM. Generated by scripts/gen_scroller.py.
 *   message:   "JOURNEY BY VADIM KOLONTSOV * JUST 2 ASIC TILES * NYAN CAT MAGIC * CORDIC * DITHER * CHIPTUNE *"
 *   text buf:  128 chars (20 leading spaces + msg)
 *   glyphs:    24 unique inline (cols layout, case style)
 */

`default_nettype none

module scroller_rom (
    input  wire [2:0]  text_y,
    input  wire [11:0] text_x,
    output wire        pixel
);

    wire [6:0] char_addr = text_x[11:5];

    // Text ROM: char_addr -> char_idx (idx 0 = ' ')
    logic [4:0] char_idx;
    always_comb begin
        case (char_addr)
            7'd20: char_idx = 5'd6;
            7'd21: char_idx = 5'd1;
            7'd22: char_idx = 5'd9;
            7'd23: char_idx = 5'd21;
            7'd24: char_idx = 5'd3;
            7'd25: char_idx = 5'd8;
            7'd26: char_idx = 5'd10;
            7'd28: char_idx = 5'd15;
            7'd29: char_idx = 5'd10;
            7'd31: char_idx = 5'd14;
            7'd32: char_idx = 5'd12;
            7'd33: char_idx = 5'd23;
            7'd34: char_idx = 5'd4;
            7'd35: char_idx = 5'd11;
            7'd37: char_idx = 5'd20;
            7'd38: char_idx = 5'd1;
            7'd39: char_idx = 5'd16;
            7'd40: char_idx = 5'd1;
            7'd41: char_idx = 5'd3;
            7'd42: char_idx = 5'd5;
            7'd43: char_idx = 5'd18;
            7'd44: char_idx = 5'd1;
            7'd45: char_idx = 5'd14;
            7'd47: char_idx = 5'd22;
            7'd49: char_idx = 5'd6;
            7'd50: char_idx = 5'd9;
            7'd51: char_idx = 5'd18;
            7'd52: char_idx = 5'd5;
            7'd54: char_idx = 5'd17;
            7'd56: char_idx = 5'd12;
            7'd57: char_idx = 5'd18;
            7'd58: char_idx = 5'd4;
            7'd59: char_idx = 5'd2;
            7'd61: char_idx = 5'd5;
            7'd62: char_idx = 5'd4;
            7'd63: char_idx = 5'd16;
            7'd64: char_idx = 5'd8;
            7'd65: char_idx = 5'd18;
            7'd67: char_idx = 5'd22;
            7'd69: char_idx = 5'd3;
            7'd70: char_idx = 5'd10;
            7'd71: char_idx = 5'd12;
            7'd72: char_idx = 5'd3;
            7'd74: char_idx = 5'd2;
            7'd75: char_idx = 5'd12;
            7'd76: char_idx = 5'd5;
            7'd78: char_idx = 5'd11;
            7'd79: char_idx = 5'd12;
            7'd80: char_idx = 5'd7;
            7'd81: char_idx = 5'd4;
            7'd82: char_idx = 5'd2;
            7'd84: char_idx = 5'd22;
            7'd86: char_idx = 5'd2;
            7'd87: char_idx = 5'd1;
            7'd88: char_idx = 5'd21;
            7'd89: char_idx = 5'd23;
            7'd90: char_idx = 5'd4;
            7'd91: char_idx = 5'd2;
            7'd93: char_idx = 5'd22;
            7'd95: char_idx = 5'd23;
            7'd96: char_idx = 5'd4;
            7'd97: char_idx = 5'd5;
            7'd98: char_idx = 5'd13;
            7'd99: char_idx = 5'd8;
            7'd100: char_idx = 5'd21;
            7'd102: char_idx = 5'd22;
            7'd104: char_idx = 5'd2;
            7'd105: char_idx = 5'd13;
            7'd106: char_idx = 5'd4;
            7'd107: char_idx = 5'd19;
            7'd108: char_idx = 5'd5;
            7'd109: char_idx = 5'd9;
            7'd110: char_idx = 5'd3;
            7'd111: char_idx = 5'd8;
            7'd113: char_idx = 5'd22;
            default: char_idx = 5'd0;
        endcase
    end

    // Column ROM: {char_idx, glyph_x} -> 8-bit glyph column (bit 0 = top pixel)
    wire [2:0] glyph_x = text_x[4:2];
    logic [7:0] font_col;
    always_comb begin
        case ({char_idx, glyph_x})
            8'd9: font_col = 8'h3E;
            8'd10: font_col = 8'h7F;
            8'd11: font_col = 8'h79;
            8'd12: font_col = 8'h61;
            8'd13: font_col = 8'h61;
            8'd14: font_col = 8'h7F;
            8'd15: font_col = 8'h3E;
            8'd17: font_col = 8'h3E;
            8'd18: font_col = 8'h7F;
            8'd19: font_col = 8'h79;
            8'd20: font_col = 8'h61;
            8'd21: font_col = 8'h61;
            8'd22: font_col = 8'h73;
            8'd23: font_col = 8'h32;
            8'd25: font_col = 8'h7F;
            8'd26: font_col = 8'h7F;
            8'd27: font_col = 8'h79;
            8'd28: font_col = 8'h01;
            8'd29: font_col = 8'h01;
            8'd30: font_col = 8'h7F;
            8'd31: font_col = 8'h7E;
            8'd33: font_col = 8'h61;
            8'd34: font_col = 8'h61;
            8'd35: font_col = 8'h79;
            8'd36: font_col = 8'h7F;
            8'd37: font_col = 8'h7F;
            8'd38: font_col = 8'h61;
            8'd39: font_col = 8'h61;
            8'd41: font_col = 8'h01;
            8'd42: font_col = 8'h01;
            8'd43: font_col = 8'h79;
            8'd44: font_col = 8'h7F;
            8'd45: font_col = 8'h7F;
            8'd46: font_col = 8'h01;
            8'd47: font_col = 8'h01;
            8'd49: font_col = 8'h30;
            8'd50: font_col = 8'h70;
            8'd51: font_col = 8'h60;
            8'd52: font_col = 8'h60;
            8'd53: font_col = 8'h78;
            8'd54: font_col = 8'h7F;
            8'd55: font_col = 8'h3F;
            8'd57: font_col = 8'h3E;
            8'd58: font_col = 8'h7F;
            8'd59: font_col = 8'h79;
            8'd60: font_col = 8'h61;
            8'd61: font_col = 8'h69;
            8'd62: font_col = 8'h7B;
            8'd63: font_col = 8'h3A;
            8'd65: font_col = 8'h3E;
            8'd66: font_col = 8'h7F;
            8'd67: font_col = 8'h79;
            8'd68: font_col = 8'h69;
            8'd69: font_col = 8'h69;
            8'd70: font_col = 8'h61;
            8'd71: font_col = 8'h61;
            8'd73: font_col = 8'h3F;
            8'd74: font_col = 8'h7F;
            8'd75: font_col = 8'h78;
            8'd76: font_col = 8'h60;
            8'd77: font_col = 8'h60;
            8'd78: font_col = 8'h7F;
            8'd79: font_col = 8'h3F;
            8'd81: font_col = 8'h67;
            8'd82: font_col = 8'h6F;
            8'd83: font_col = 8'h68;
            8'd84: font_col = 8'h68;
            8'd85: font_col = 8'h68;
            8'd86: font_col = 8'h7F;
            8'd87: font_col = 8'h3F;
            8'd89: font_col = 8'h7F;
            8'd90: font_col = 8'h7F;
            8'd91: font_col = 8'h7B;
            8'd92: font_col = 8'h06;
            8'd93: font_col = 8'h03;
            8'd94: font_col = 8'h7F;
            8'd95: font_col = 8'h7F;
            8'd97: font_col = 8'h7E;
            8'd98: font_col = 8'h7F;
            8'd99: font_col = 8'h79;
            8'd100: font_col = 8'h09;
            8'd101: font_col = 8'h09;
            8'd102: font_col = 8'h7F;
            8'd103: font_col = 8'h7E;
            8'd105: font_col = 8'h7F;
            8'd106: font_col = 8'h7F;
            8'd107: font_col = 8'h78;
            8'd108: font_col = 8'h08;
            8'd109: font_col = 8'h08;
            8'd110: font_col = 8'h7F;
            8'd111: font_col = 8'h7F;
            8'd113: font_col = 8'h03;
            8'd114: font_col = 8'h0F;
            8'd115: font_col = 8'h3C;
            8'd116: font_col = 8'h70;
            8'd117: font_col = 8'h3C;
            8'd118: font_col = 8'h0F;
            8'd119: font_col = 8'h03;
            8'd121: font_col = 8'h7F;
            8'd122: font_col = 8'h7F;
            8'd123: font_col = 8'h79;
            8'd124: font_col = 8'h69;
            8'd125: font_col = 8'h69;
            8'd126: font_col = 8'h7F;
            8'd127: font_col = 8'h36;
            8'd129: font_col = 8'h3F;
            8'd130: font_col = 8'h7F;
            8'd131: font_col = 8'h78;
            8'd132: font_col = 8'h60;
            8'd133: font_col = 8'h60;
            8'd134: font_col = 8'h60;
            8'd135: font_col = 8'h60;
            8'd137: font_col = 8'h72;
            8'd138: font_col = 8'h7B;
            8'd139: font_col = 8'h79;
            8'd140: font_col = 8'h69;
            8'd141: font_col = 8'h69;
            8'd142: font_col = 8'h6F;
            8'd143: font_col = 8'h66;
            8'd145: font_col = 8'h66;
            8'd146: font_col = 8'h6F;
            8'd147: font_col = 8'h69;
            8'd148: font_col = 8'h69;
            8'd149: font_col = 8'h69;
            8'd150: font_col = 8'h7B;
            8'd151: font_col = 8'h32;
            8'd153: font_col = 8'h7F;
            8'd154: font_col = 8'h7F;
            8'd155: font_col = 8'h79;
            8'd156: font_col = 8'h09;
            8'd157: font_col = 8'h09;
            8'd158: font_col = 8'h0F;
            8'd159: font_col = 8'h06;
            8'd161: font_col = 8'h7F;
            8'd162: font_col = 8'h7F;
            8'd163: font_col = 8'h78;
            8'd164: font_col = 8'h1C;
            8'd165: font_col = 8'h36;
            8'd166: font_col = 8'h63;
            8'd167: font_col = 8'h41;
            8'd169: font_col = 8'h7F;
            8'd170: font_col = 8'h7F;
            8'd171: font_col = 8'h79;
            8'd172: font_col = 8'h19;
            8'd173: font_col = 8'h39;
            8'd174: font_col = 8'h6F;
            8'd175: font_col = 8'h46;
            8'd177: font_col = 8'h04;
            8'd178: font_col = 8'h6C;
            8'd179: font_col = 8'h3C;
            8'd180: font_col = 8'h1F;
            8'd181: font_col = 8'h3C;
            8'd182: font_col = 8'h6C;
            8'd183: font_col = 8'h04;
            8'd185: font_col = 8'h7F;
            8'd186: font_col = 8'h7F;
            8'd187: font_col = 8'h79;
            8'd188: font_col = 8'h61;
            8'd189: font_col = 8'h61;
            8'd190: font_col = 8'h7F;
            8'd191: font_col = 8'h3E;
            default: font_col = 8'h00;
        endcase
    end

    // Column bit: font_col[text_y]
    assign pixel = font_col[text_y];

    wire _unused = &{text_x[1:0], 1'b0};

endmodule
